# 에러를 반환하는 메서드 테스트하기

## 211112_TIL

## 목차 
- [학습 내용](#학습-내용) 
- [고민된 점 ](#고민된-점)
- [해결 방법](#해결-방법)


## 학습 내용

### `XCTAssertThrowsError`와 `XCTAssertNoThrow`

TDD 기반으로 프로젝트를 진행하던 중 에러를 던져주는 메서드는 어떻게 테스트해야하지 고민해봤다.

찾아보니 역시... 던져지는 에러가 내가 의도한 에러가 맞는지 비교해주는 메서드가 있었다. 

```swift
public func XCTAssertThrowsError<T>(_ expression: @autoclosure () throws -> T, _ message: @autoclosure () -> String = "", file: StaticString = #filePath
, line: UInt = #line, _ errorHandler: (Error) -> Void = { _ in })
```

보이는가... 수많은 파라미터들... 우선 하나씩 살펴보자. 

> 1 . `expression: @autoclosure () throws -> T`

 에러를 던질 수 있는 구문이 들어갈 자리다. 저 부분에 에러를 던질 수 있는 메서드(`try canThrowError()`) 가 들어가면 된다. 
 
> 2 . `message: @autoclosure () -> String = ""`

엇 지난번 클로저 공부할 때 봤던 `@autoclosure`다. 기억을 되짚어보면 저 키워드를 추가해줌으로 인해 반환값 타입을 그냥 저 파라미터 위치에 넣어줄 수 있었다. 

여기서는 에러에 대한 설명이 들어간다. 하지만 필수적으로 구현하지는 않아도 된다. 

> 3. `file: StaticString = #filePath`

에러가 발생할 수 있는 파일을 가리킨다. 테스트하는 메서드가 속한 파일의 이름을 기본적으로 가리킨다. 

하지만 이 또한 필수는 아님!
(기본적으로 다 되는건가..?)

> 4. `line: UInt = #line`

에러가 발생할 수 있는 코드 라인이다. 기본적으로는 테스트하려는 메서드의 코드 라인 넘버를 가리킨다. 

음.. 이것도 필수는 아님! 
(이것도 기본적으로 다 되는건가..?)

> 5. `_ errorHandler: (Error) -> Void = { _ in }`

계속 다 필수는 아니라고 했는데, 이 부분은 좀 중요하다! 

말 그대로 에러 핸들러로, 내가 테스트하기 위해 발생시킨 에러가 예상한 에러가 맞는지 확인하는데 사용될 수 있다. 

이제 파라미터는 다 봤으니 실제 사용법을 봐보자. 

```swift
enum SystemError {
	case networkError
}

func canThrowError(event: String) throws -> String {
	if event == "네트워크 장애" {
		throw SystemError.networkError
	}
	
	return "아무 일 없음"
}
```

임의로 만든 메서드와 에러 타입을 보자. 내용이 중요한 건 아니고 에러를 던질 수 있는 메서드가 있다는 게 중요한 것이다!

이제 그러면 단위 테스트로 와서 event 파라미터에 "네트워크 장애"라는 값이 들어왔을 때 알맞는 에러를 반환하는지 테스트 해보자. 

```swift
func test_네트워크_장애가_발생하면_에러를_반환하는지() {
	XCTAssertThrowsError(try canThrowError(event: "네트워크 장애")) { error in 
		XCTAssertEqual(error as? SystemError, SystemError.networkError)
	}
}
```

아까 위에서 파라미터들 봤던 것 처럼 `expression` 쪽에는 에러를 발생시킬 수 있는 메서드를 실행시켜준다. 

그리고 아까 중간에 있던 message, file, line은 다 패스하고 발생한 에러를 가지고 비교해보기 위해 errorHandler를 이용해보자. 

error라는 파라미터로 에러를 받고, 이제 우리가 예상한 에러와 같은지 살펴보기 위해 `XCTAssertEqual` 메서드를 사용해준다. 아까 받은 error는 `Error`타입이기 때문에 `SystemError` 타입으로 다운캐스팅 해준다. 그리고 우리가 예상한 에러인 `SystemError.networkError`와 비교해주면 된다! 

그리고 테스트를 실행하면... 성공..! 

자매품으로 `XCTAssertNoThrow()`도 있다. 파라미터는 `XCTAssertThrowsError`와 거의 같은데 `XCTAssertNoThrow()`는 에러가 발생하지 않는 경우이기에 errorHandler만 없고 다른 파라미터는 다 있다. 

사용 방법은 더 간단하다. 

```swift
func test_다른_문제가_발생하면_에러를_반환하는지() {
	XCTAssertNoThrow(try canThrowError(event: "다른 일"))
}
```

이렇게만 적어주면 해당 메서드는 에러 자체를 반환하지 않기에 테스트 또한 통과할 수 있다. 

### NumberFormatter

숫자값과 텍스트 표현 사이에서 변환을 해주는 역할을 한다. 

```swift
open func string(from number: NSNumber) -> String?

open func number(from string: String) -> NSNumber?
```

위 처럼 `NSNumber`를 받아 `String` 으로 변환해주기도 하며,  `String`를 받아 `NSNumber` 으로 변환해주기도 한다. 다만 변환되는 값들은 모두 옵셔널이니 사용시에 주의해야 할 것 같다. 

주로 이를 활용해서 자릿수를 제한하거나, 단위를 관리할 수 도 있다. 

```swift
// 표현 스타일을 정한다.
// .decimal : 3자리마다 쉼표를 찍어준다
format.numberStyle = .decimal
// 소수점 자리수를 정한다
format.maximumFractionDigits = 4 // 소수점은 4자리까지만
format.string(from: 123456789.1234567891234) // 123,456,789.1235
// 정수형 자리수를 정한다
format.maximumIntegerDigits = 4 // 정수형 부분을 4자리까지만
format.string(from: 123456789.1234567891234) // 6,789.1235
// 어느 자리수에서 반올림/올림/버림 할건지
format.roundingMode = .halfUp // 반올림 
```

`.numberStyle`([numberStyle](https://developer.apple.com/documentation/foundation/numberformatter/style))과 `.roundingMode`([roundingMode](https://developer.apple.com/documentation/foundation/numberformatter/roundingmode)) 에는 다양한 표현 방식들이 존재한다. 이는 공식문서에서 확인해보자! 

## 고민된 점 

- Unit Test를 할 때 `XCTAssertEqual`말고도 다른게 있는가? 

## 해결 방법 

- 정말 여러가지 방법의 테스트 방법이 있다. 그 중에서 한 가지를 학습 내용에 정리!
---

**Ref**

[XCTAssertThrowsError-Apple](https://developer.apple.com/documentation/xctest/1500795-xctassertthrowserror)
[XCTAssertThrowsError](https://www.appsdeveloperblog.com/xctassertthrowserror-assertion-example/)
[NumberFormatter.Style](https://developer.apple.com/documentation/foundation/numberformatter/style)
